import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { parsePobCode, decodePobCode, parseXml } from '../src/services/pobParser'
import { resolvePobRawUrl } from '../src/data/pob'

/**
 * Fixtures: test/fixtures/pob-{leveling,endgame}.txt — real-FORMAT PoB export codes
 * (base64url(zlib(XML)), the exact export pipeline), authored to PoB's schema and
 * regenerated by scripts/make-pob-fixtures.mjs. They exercise decode + parse on
 * genuine export-format data (a leveling stage and an endgame build).
 */
const fixture = (n: string) => readFileSync(fileURLToPath(new URL(`./fixtures/pob-${n}.txt`, import.meta.url)), 'utf8')

describe('resolvePobRawUrl', () => {
  it('maps pobb.in build links to /raw', () => {
    expect(resolvePobRawUrl('https://pobb.in/abc123').url).toBe('https://pobb.in/abc123/raw')
    expect(resolvePobRawUrl('https://pobb.in/u/someone/MyBuild').url).toBe('https://pobb.in/u/someone/MyBuild/raw')
  })
  it('maps pastebin links to raw, and leaves already-raw pastebin alone', () => {
    expect(resolvePobRawUrl('https://pastebin.com/AbCdEf12').url).toBe('https://pastebin.com/raw/AbCdEf12')
    expect(resolvePobRawUrl('https://pastebin.com/raw/AbCdEf12').url).toBe('https://pastebin.com/raw/AbCdEf12')
  })
  it('treats a non-URL as a raw pasted code', () => {
    const r = resolvePobRawUrl('eJzLSM3JyQcABiwCFQ==')
    expect(r.url).toBeNull()
    expect(r.source.kind).toBe('raw')
  })
})

describe('decodePobCode', () => {
  it('decodes base64url(zlib(xml)) to PoB XML', () => {
    const xml = decodePobCode(fixture('leveling'))
    expect(xml).toContain('<PathOfBuilding')
    expect(xml).toContain('className="Witch"')
  })
  it('rejects a non-PoB blob with a clear error', () => {
    expect(() => decodePobCode('not-a-valid-code!!!')).toThrow()
  })
})

describe('parseXml (minimal)', () => {
  it('reads attributes, nesting and text bodies', () => {
    const n = parseXml('<A x="1"><B y="2">hello</B><C z="3"/></A>')!
    expect(n.tag).toBe('A')
    expect(n.attrs.x).toBe('1')
    expect(n.children.map(c => c.tag)).toEqual(['B', 'C'])
    expect(n.children[0].text).toBe('hello')
    expect(n.children[1].attrs.z).toBe('3')
  })
  it('decodes entities in attributes and text', () => {
    const n = parseXml('<A t="a &amp; b">x &lt; y</A>')!
    expect(n.attrs.t).toBe('a & b')
    expect(n.text).toBe('x < y')
  })
})

describe('parsePobCode — leveling stage', () => {
  const p = parsePobCode(fixture('leveling'))
  it('captures class/ascendancy/level', () => {
    expect(p.className).toBe('Witch')
    expect(p.ascendancy).toBe('') // "None" normalized away
    expect(p.level).toBe(42)
  })
  it('captures gem links by slot and the main skill', () => {
    expect(p.mainSkill).toBe('Freezing Pulse')
    const main = p.skillGroups.find(g => g.main)!
    expect(main.slot).toBe('Weapon 1')
    expect(main.gems.map(g => g.name)).toContain('Added Cold Damage Support')
    expect(main.gems.find(g => g.name === 'Added Cold Damage Support')!.support).toBe(true)
    expect(main.gems.find(g => g.name === 'Freezing Pulse')!.support).toBe(false)
  })
  it('captures equipped items with slots + mods', () => {
    const boots = p.items.find(i => i.slot === 'Boots')!
    expect(boots.mods.some(m => /Movement Speed/.test(m))).toBe(true)
  })
  it('captures PoB-reported stats and the tree spec', () => {
    expect(p.stats.Life).toBe(1240)
    expect(p.trees[0].nodeCount).toBe(25)
    expect(p.progression[0]).toEqual({ title: 'Leveling', nodeCount: 25 })
  })
})

describe('parsePobCode — endgame build', () => {
  const p = parsePobCode(fixture('endgame'))
  it('captures ascendancy, main skill and support links', () => {
    expect(p.className).toBe('Witch')
    expect(p.ascendancy).toBe('Necromancer')
    expect(p.level).toBe(95)
    expect(p.mainSkill).toBe('Raise Spectre')
    const main = p.skillGroups.find(g => g.main)!
    expect(main.gems.filter(g => g.support).length).toBe(3)
  })
  it('captures uniques + rares by slot with headline stats', () => {
    expect(p.items.find(i => i.slot === 'Body Armour')!.name).toBe('Belly of the Beast')
    expect(p.items.find(i => i.slot === 'Belt')!.name).toBe('Headhunter')
    expect(p.items.find(i => i.slot === 'Ring 1')!.rarity).toBe('RARE')
    expect(p.stats.Life).toBe(5200)
    expect(p.stats.TotalDPS).toBe(3550000)
  })
  it('captures allocated node ids (names resolved later via the tree)', () => {
    expect(p.trees[0].nodeCount).toBe(109)
    expect(p.trees[0].nodeIds).toContain(100)
    expect(p.trees[0].nodeIds).toContain(300)
  })
})
